apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 2  # Number of replicas/pods to run
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow-container
        image: <your-docker-image>:latest  # Replace with your Docker image name and tag
        ports:
        - containerPort: 4499
        env:
        - name: LC_ALL
          value: "en_US.UTF-8"
        - name: LANG
          value: "en_US.UTF-8"
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4499
  type: LoadBalancer  # You can use 'ClusterIP' if you do not need external access
